// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU9_HfGhucrkaoNB4AbW_I_4hOgkz1j4E',
    appId: '1:142318020716:android:0fcb0fc0fe3897d8d39049',
    messagingSenderId: '142318020716',
    projectId: 'money-trace',
    storageBucket: 'money-trace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3_2P4xSIGgbmFeCZTchY_Xc8lcrrwhgo',
    appId: '1:142318020716:ios:265b3ed921da6ba7d39049',
    messagingSenderId: '142318020716',
    projectId: 'money-trace',
    storageBucket: 'money-trace.appspot.com',
    iosClientId: '142318020716-dvdp37brb94jvvsel057hiupn6qoct67.apps.googleusercontent.com',
    iosBundleId: 'com.wml.expensesmanager.expenseManager',
  );
}
